name: Run extension tests on CPU
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: 'AUTOMATIC1111/stable-diffusion-webui'
          path: 'stable-diffusion-webui'

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: 'ModelSurge/sd-webui-comfyui'
          path: 'stable-diffusion-webui/extensions/sd-webui-comfyui'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: pip
          cache-dependency-path: |
            **/requirements*txt
            stable-diffusion-webui/requirements*txt

      - name: Install dependencies
        run: |
          cd stable-diffusion-webui/extensions/sd-webui-comfyui
          pip install -r requirements.txt
          cd ../..
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd stable-diffusion-webui
          python launch.py --no-half --disable-opt-split-attention --use-cpu all --skip-torch-cuda-test --api --tests ./extensions/sd-webui-comfyui/tests
